/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#636565',
        'on-secondary-fixed': '#1a1b22',
        'on-secondary-container': '#bcbbc5',
        'on-tertiary': '#303033',
        'surface-variant': '#353437',
        secondary: '#c6c5cf',
        'on-primary-fixed-variant': '#454747',
        'surface-dim': '#131315',
        surface: '#131315',
        'surface-bright': '#39393b',
        'tertiary-fixed': '#e4e1e5',
        'surface-tint': '#c6c6c7',
        'tertiary-container': '#e4e1e5',
        'surface-container': '#201f22',
        'on-secondary': '#2f3038',
        'on-secondary-fixed-variant': '#46464e',
        background: '#131315',
        'on-tertiary-fixed-variant': '#47464a',
        'error-container': '#93000a',
        'surface-container-lowest': '#0e0e10',
        'secondary-fixed': '#e3e1ec',
        'outline-variant': '#444748',
        primary: '#ffffff',
        'inverse-primary': '#5d5f5f',
        'secondary-fixed-dim': '#c6c5cf',
        'surface-container-highest': '#353437',
        'primary-fixed': '#e2e2e2',
        'on-surface-variant': '#c4c7c8',
        tertiary: '#ffffff',
        'on-background': '#e5e1e4',
        'on-primary': '#2f3131',
        'on-tertiary-fixed': '#1b1b1e',
        'inverse-surface': '#e5e1e4',
        error: '#ffb4ab',
        'on-primary-fixed': '#1a1c1c',
        'inverse-on-surface': '#313032',
        'tertiary-fixed-dim': '#c8c6c9',
        'on-tertiary-container': '#656467',
        'surface-container-high': '#2a2a2c',
        'primary-container': '#e2e2e2',
        'secondary-container': '#4a4b53',
        outline: '#8e9192',
        'on-surface': '#e5e1e4',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#1c1b1d',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        'item-gap': '8px',
        'sidebar-width': '260px',
        unit: '4px',
        'toolbar-height': '40px',
        'panel-padding': '12px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        label: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
